### ISSUE TITLE
Coding Conventions

### ISSUE THREAD

**Issue by ghost** [FreeCodeCampGuam/freecodecampguam.github.io#1]
I think we can follow Google's HTML/CSS style guide and Airbnb's JavaScript style guide. What do you guys think? 

Airbnb https://github.com/airbnb/javascript
Google https://google.github.io/styleguide/htmlcssguide.xml

**Comment by Chovin** [comment]
Can you explain what you mean?

Are you asking if we should always do this or just on this project?
How much are we enforcing this?
Why do you think we should do this? What's the reasoning etc?

**Comment by rcmanglona** [comment]
Using a style guide is a good idea. It will make things more cohesive and sustainable. 

Here's another helpful link. I've going through their responsive web dev stuff.
[https://developers.google.com/web/](https://developers.google.com/web/)

**Comment by ghost** [comment]
We can adopt these guides just for this project since we all have our preferred styles. This will benefit code maintainability between contributors, and it will increase our productivity during collaboration. 

We should try our best to implement these styles to keep our code clean and readable. If someone fails to comply or makes a mistake, we can kindly provide input to the individual.

**Comment by Chovin** [comment]
no longer editing Bootstrap's (or other libraries') source code as per #19
