### ISSUE TITLE
Website format/design

### ISSUE THREAD

**Issue by ghost** [FreeCodeCampGuam/freecodecampguam.github.io#25]
We need to come up with a structure for each page of the website. Also, do we really want to list each project on its own page, or should we just list all projects on one web that looks similar to the home page?

**Comment by Chovin** [comment]
I assumed we'd list all projects on 1 page in some way. each project can have it's own little mini-page or expansion with info that links to outside resources. *shrug
ideas

**Comment by ghost** [comment]
Do we want to have a contact us form, or do we just want to list contact information?

We should also finalize what we're going to do for the projects page.

**Comment by Chovin** [comment]
@twinkle85 said she'll work on wireframes and user stories and whatnot. we completely skipped that phase.
let's keep working on the code and we'll adjust when those get done
